// 导入全局样式文件
import './globals.css'
// 导入 Next.js 的 Metadata 类型
import type { Metadata } from 'next'
// 导入 Google 字体 Inter
import { Inter } from 'next/font/google'

import { ClerkProvider } from '@clerk/nextjs'
// 使用 Inter 字体，并指定子集为拉丁字母
const inter = Inter({ subsets: ['latin'] })
import { Providers } from './providers'

// 定义页面的元数据
export const metadata: Metadata = {
  title: 'Create Next App', // 页面标题
  description: 'Generated by create next app', // 页面描述
}

// 定义根布局组件
export default function RootLayout({
  children, // 子组件
}: {
  children: React.ReactNode // 子组件的类型是 React 节点
}) {
  return (
    <html lang="en" data-theme='light'> 
      <body className={inter.className}>
        <ClerkProvider>
              <Providers>
            {children}
            </Providers>
          </ClerkProvider>
        </body>
    </html>
  )
}